#!/usr/bin/env python3
"""Generate native Apple and Android localization resources from one catalogue."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HERE = ROOT / "i18n"
LOCALES = HERE / "locales"

# Locale -> (Android qualifier, Apple lproj).
SUPPORTED = {
    "en": ("", "en"), "es": ("es", "es"), "pt-BR": ("b+pt+BR", "pt-BR"),
    "fr": ("fr", "fr"), "de": ("de", "de"), "it": ("it", "it"),
    "ar": ("ar", "ar"), "tr": ("tr", "tr"), "ru": ("ru", "ru"),
    "zh-Hans": ("b+zh+Hans", "zh-Hans"), "ja": ("ja", "ja"), "ko": ("ko", "ko"),
    "th": ("th", "th"), "id": ("in", "id"), "vi": ("vi", "vi"),
    "nl": ("nl", "nl"), "pl": ("pl", "pl"), "ro": ("ro", "ro"),
    "el": ("el", "el"), "uk": ("uk", "uk"), "hi": ("hi", "hi"),
    "ms": ("ms", "ms"), "zh-Hant": ("b+zh+Hant", "zh-Hant"),
    "sv": ("sv", "sv"), "cs": ("cs", "cs"),
}

INFO_KEYS = {
    "permissions.photo_library": "NSPhotoLibraryUsageDescription",
    "permissions.photo_library_add": "NSPhotoLibraryAddUsageDescription",
}


def load(code: str) -> dict[str, str]:
    return json.loads((LOCALES / f"{code}.json").read_text(encoding="utf-8"))["strings"]


def apple_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def android_escape(value: str) -> str:
    # Android requires positional placeholders when a resource contains more than one
    # substitution. Number every placeholder so translations stay safe if words move.
    # Apple's `%@` maps to Java's `%s`; `%,d` keeps its grouping flag as `%1$,d`.
    index = 0

    def positional(match: re.Match[str]) -> str:
        nonlocal index
        index += 1
        flags, kind = match.groups()
        return f"%{index}${flags}{'s' if kind == '@' else kind}"

    value = re.sub(r"%(?!%)(,?)([@ds])", positional, value)
    return (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n").replace("@", "\\@"))


def android_name(key: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", key.lower().replace(".", "_"))


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    base = load("en")
    for code, (qualifier, lproj) in SUPPORTED.items():
        translated = load(code)
        values = {key: translated.get(key, source) for key, source in base.items()}

        apple = [f"/* Generated by i18n/build.py from locales/{code}.json — do not edit. */", ""]
        for key, source in base.items():
            apple.append(f'"{apple_escape(source)}" = "{apple_escape(values[key])}";')
        write(ROOT / f"ios/SmartStorage/Resources/Localization/{lproj}.lproj/Localizable.strings", "\n".join(apple) + "\n")

        info = [f"/* Generated by i18n/build.py from locales/{code}.json — do not edit. */", ""]
        for key, plist_key in INFO_KEYS.items():
            info.append(f'"{plist_key}" = "{apple_escape(values[key])}";')
        write(ROOT / f"ios/SmartStorage/Resources/Localization/{lproj}.lproj/InfoPlist.strings", "\n".join(info) + "\n")

        android = ['<?xml version="1.0" encoding="utf-8"?>',
                   f'<!-- Generated by i18n/build.py from locales/{code}.json — do not edit. -->',
                   "<resources>",
                   '    <string name="app_name" translatable="false">KeepSpace</string>']
        for key in base:
            android.append(f'    <string name="{android_name(key)}">{android_escape(values[key])}</string>')
        android.append("</resources>")
        folder = "values" if not qualifier else f"values-{qualifier}"
        write(ROOT / f"android/app/src/main/res/{folder}/strings.xml", "\n".join(android) + "\n")

    # Android keeps readable English in call sites; this generated map connects it to
    # compile-time checked resource IDs without reflection or resource-name hashing.
    entries = []
    for key, source in base.items():
        escaped = source.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("$", "\\$")
        entries.append(f'        "{escaped}" to R.string.{android_name(key)},')
    kotlin = """// Generated by i18n/build.py — do not edit.\npackage com.smartstorage.cleaner.ui.i18n\n\nimport com.smartstorage.cleaner.R\n\ninternal object I18nCatalog {\n    val resources: Map<String, Int> = mapOf(\n%s\n    )\n}\n""" % "\n".join(entries)
    write(ROOT / "android/app/src/main/java/com/smartstorage/cleaner/ui/i18n/I18nCatalog.kt", kotlin)
    print(f"built {len(SUPPORTED)} locales with {len(base)} strings")


if __name__ == "__main__":
    main()
